---

- name: PostgreSQL paketleri kuruluyor
  apt: 
    name:
      - postgresql
      - python-psycopg2

- name: PHP PostgreSQL paketleri kuruluyor
  apt: 
    name:
      - php-pgsql

- name: PostgreSQL servisi ayağa kaldırılıyor
  service: name=postgresql state=started enabled=yes

- name: Veritabanı oluştur
  sudo_user: postgres
  postgresql_db: name={{ db_name }}
                 encoding='UTF-8'
                 lc_collate='en_US.UTF-8'
                 lc_ctype='en_US.UTF-8'
                 template='template0'
                 state=present

- name: Veritabanı erişimleri ayarlanıyor
  sudo_user: postgres
  postgresql_user: db={{ db_name }}
                   name={{ db_user }}
                   password={{ db_password }}
                   priv=ALL
                   state=present

- name: Veritabanı erişim yetki kısıtları ayarlanıyor
  sudo_user: postgres
  postgresql_user: name={{ db_user }}
                   role_attr_flags=NOSUPERUSER,NOCREATEDB
                   state=present

