- name: Nextcloud Sunucu Kurulumu(PostgreSQL)
  hosts: server
  sudo: yes
  sudo_user: root
  vars_files:
    - vars/main.yml

  roles:
  - phpsettings
  - installnextcloud
  - createdb
  - apachesettings
  - installredis
